name: movil
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3 # Or latest version
  equatable: ^2.0.5
  shared_preferences: ^2.2.2 # Or latest version
  flutter_colorpicker: ^1.0.3 # Or latest version
  # --- CHANGE THIS LINE ---
  lucide_icons: ^0.257.0 # Use the suggested version
  # --- END CHANGE ---
  cupertino_icons: ^1.0.8  
  dio: ^5.4.0 # Para llamadas API
  flutter_secure_storage: ^9.0.0 # Para guardar token JWT

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
